"""Simple semantic retrieval over the SHL assessment catalog.

This module loads the FAISS index and metadata generated by build_index.py and
returns the most relevant assessments for a user query.
"""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer


REPO_ROOT = Path(__file__).resolve().parents[1]
FAISS_INDEX_PATH = REPO_ROOT / "data" / "faiss.index"
METADATA_PATH = REPO_ROOT / "data" / "metadata.pkl"
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


class AssessmentRetriever:
    """Semantic retriever for SHL assessments."""

    def __init__(self, index_path: Path = FAISS_INDEX_PATH, metadata_path: Path = METADATA_PATH):
        self.index_path = index_path
        self.metadata_path = metadata_path
        self.model = SentenceTransformer(EMBEDDING_MODEL_NAME)
        self.index = faiss.read_index(str(index_path))
        with metadata_path.open("rb") as handle:
            self.metadata = pickle.load(handle)

    def _embed_query(self, query: str) -> np.ndarray:
        """Embed a single user query."""

        embedding = self.model.encode([query], convert_to_numpy=True, normalize_embeddings=True)
        return embedding.astype("float32")

    def search(self, query: str, top_k: int = 5) -> List[Dict[str, Any]]:
        """Return the top-k most relevant assessments for a query."""

        query_embedding = self._embed_query(query)
        scores, indices = self.index.search(query_embedding, top_k)

        results: List[Dict[str, Any]] = []
        for score, index in zip(scores[0], indices[0]):
            if index < 0:
                continue
            metadata = self.metadata[int(index)]
            results.append({
                "score": float(score),
                **metadata,
            })
        return results


def build_retriever() -> AssessmentRetriever:
    """Create a retriever instance using the current index files."""

    return AssessmentRetriever()


if __name__ == "__main__":
    retriever = build_retriever()
    sample_queries = [
        "Java developer",
        "Senior leadership",
        "Python backend engineer",
        "Personality assessment",
        "Cognitive ability test",
    ]

    for query in sample_queries:
        print(f"\nQuery: {query}")
        for result in retriever.search(query, top_k=3):
            print(f"- {result['name']} | score={result['score']:.4f} | url={result['url']}")
